# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'in-PROTECC-CIVIL.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(998, 679)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 70, 1001, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.FORM = QtWidgets.QWidget()
        self.FORM.setAutoFillBackground(False)
        self.FORM.setObjectName("FORM")
        self.grupo1 = QtWidgets.QGroupBox(self.FORM)
        self.grupo1.setGeometry(QtCore.QRect(10, 20, 561, 201))
        self.grupo1.setTitle("")
        self.grupo1.setObjectName("grupo1")
        self.folio_text = QtWidgets.QLabel(self.grupo1)
        self.folio_text.setGeometry(QtCore.QRect(10, 10, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.folio_text.setFont(font)
        self.folio_text.setAlignment(QtCore.Qt.AlignCenter)
        self.folio_text.setObjectName("folio_text")
        self.folio_input = QtWidgets.QLineEdit(self.grupo1)
        self.folio_input.setGeometry(QtCore.QRect(60, 10, 71, 21))
        self.folio_input.setObjectName("folio_input")
        self.turno_text = QtWidgets.QLabel(self.grupo1)
        self.turno_text.setGeometry(QtCore.QRect(150, 10, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.turno_text.setFont(font)
        self.turno_text.setAlignment(QtCore.Qt.AlignCenter)
        self.turno_text.setObjectName("turno_text")
        self.turno_input = QtWidgets.QLineEdit(self.grupo1)
        self.turno_input.setGeometry(QtCore.QRect(210, 10, 91, 21))
        self.turno_input.setObjectName("turno_input")
        self.agente_text = QtWidgets.QLabel(self.grupo1)
        self.agente_text.setGeometry(QtCore.QRect(320, 10, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.agente_text.setFont(font)
        self.agente_text.setAlignment(QtCore.Qt.AlignCenter)
        self.agente_text.setObjectName("agente_text")
        self.agente_input = QtWidgets.QLineEdit(self.grupo1)
        self.agente_input.setGeometry(QtCore.QRect(380, 10, 91, 21))
        self.agente_input.setObjectName("agente_input")
        self.report_o_text = QtWidgets.QLabel(self.grupo1)
        self.report_o_text.setGeometry(QtCore.QRect(10, 80, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.report_o_text.setFont(font)
        self.report_o_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.report_o_text.setObjectName("report_o_text")
        self.reporte_o_input = QtWidgets.QLineEdit(self.grupo1)
        self.reporte_o_input.setGeometry(QtCore.QRect(90, 80, 101, 21))
        self.reporte_o_input.setObjectName("reporte_o_input")
        self.h_report_text = QtWidgets.QLabel(self.grupo1)
        self.h_report_text.setGeometry(QtCore.QRect(10, 110, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.h_report_text.setFont(font)
        self.h_report_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.h_report_text.setObjectName("h_report_text")
        self.h_report_input = QtWidgets.QLineEdit(self.grupo1)
        self.h_report_input.setGeometry(QtCore.QRect(90, 110, 101, 21))
        self.h_report_input.setObjectName("h_report_input")
        self.terminal_text = QtWidgets.QLabel(self.grupo1)
        self.terminal_text.setGeometry(QtCore.QRect(10, 140, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.terminal_text.setFont(font)
        self.terminal_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.terminal_text.setObjectName("terminal_text")
        self.terminal_input = QtWidgets.QLineEdit(self.grupo1)
        self.terminal_input.setGeometry(QtCore.QRect(90, 140, 101, 21))
        self.terminal_input.setObjectName("terminal_input")
        self.reporte_text = QtWidgets.QLabel(self.grupo1)
        self.reporte_text.setGeometry(QtCore.QRect(10, 170, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.reporte_text.setFont(font)
        self.reporte_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.reporte_text.setObjectName("reporte_text")
        self.reporte_input = QtWidgets.QLineEdit(self.grupo1)
        self.reporte_input.setGeometry(QtCore.QRect(90, 170, 101, 21))
        self.reporte_input.setObjectName("reporte_input")
        self.mun_region_text = QtWidgets.QLabel(self.grupo1)
        self.mun_region_text.setGeometry(QtCore.QRect(230, 80, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.mun_region_text.setFont(font)
        self.mun_region_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mun_region_text.setObjectName("mun_region_text")
        self.mun_region_input = QtWidgets.QLineEdit(self.grupo1)
        self.mun_region_input.setGeometry(QtCore.QRect(360, 80, 191, 21))
        self.mun_region_input.setObjectName("mun_region_input")
        self.colonia_text = QtWidgets.QLabel(self.grupo1)
        self.colonia_text.setGeometry(QtCore.QRect(230, 110, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.colonia_text.setFont(font)
        self.colonia_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.colonia_text.setObjectName("colonia_text")
        self.colonia_input = QtWidgets.QLineEdit(self.grupo1)
        self.colonia_input.setGeometry(QtCore.QRect(360, 110, 191, 21))
        self.colonia_input.setObjectName("colonia_input")
        self.colonia_text_2 = QtWidgets.QLabel(self.grupo1)
        self.colonia_text_2.setGeometry(QtCore.QRect(230, 140, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.colonia_text_2.setFont(font)
        self.colonia_text_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.colonia_text_2.setObjectName("colonia_text_2")
        self.colonia_input_2 = QtWidgets.QLineEdit(self.grupo1)
        self.colonia_input_2.setGeometry(QtCore.QRect(360, 140, 191, 21))
        self.colonia_input_2.setObjectName("colonia_input_2")
        self.grupo2 = QtWidgets.QGroupBox(self.FORM)
        self.grupo2.setGeometry(QtCore.QRect(10, 230, 561, 211))
        self.grupo2.setTitle("")
        self.grupo2.setObjectName("grupo2")
        self.dependencias_text = QtWidgets.QLabel(self.grupo2)
        self.dependencias_text.setGeometry(QtCore.QRect(10, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.dependencias_text.setFont(font)
        self.dependencias_text.setAlignment(QtCore.Qt.AlignCenter)
        self.dependencias_text.setObjectName("dependencias_text")
        self.dependencias_input = QtWidgets.QTextEdit(self.grupo2)
        self.dependencias_input.setGeometry(QtCore.QRect(10, 50, 231, 131))
        self.dependencias_input.setObjectName("dependencias_input")
        self.acciones_text = QtWidgets.QLabel(self.grupo2)
        self.acciones_text.setGeometry(QtCore.QRect(320, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.acciones_text.setFont(font)
        self.acciones_text.setAlignment(QtCore.Qt.AlignCenter)
        self.acciones_text.setObjectName("acciones_text")
        self.acciones_input = QtWidgets.QTextEdit(self.grupo2)
        self.acciones_input.setGeometry(QtCore.QRect(320, 50, 231, 131))
        self.acciones_input.setObjectName("acciones_input")
        self.grupo3 = QtWidgets.QGroupBox(self.FORM)
        self.grupo3.setGeometry(QtCore.QRect(580, 20, 401, 421))
        self.grupo3.setTitle("")
        self.grupo3.setObjectName("grupo3")
        self.afectacion_text = QtWidgets.QLabel(self.grupo3)
        self.afectacion_text.setGeometry(QtCore.QRect(10, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.afectacion_text.setFont(font)
        self.afectacion_text.setAlignment(QtCore.Qt.AlignCenter)
        self.afectacion_text.setObjectName("afectacion_text")
        self.afectacion_input = QtWidgets.QTextEdit(self.grupo3)
        self.afectacion_input.setGeometry(QtCore.QRect(10, 50, 381, 131))
        self.afectacion_input.setObjectName("afectacion_input")
        self.desarollo_text = QtWidgets.QLabel(self.grupo3)
        self.desarollo_text.setGeometry(QtCore.QRect(10, 210, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.desarollo_text.setFont(font)
        self.desarollo_text.setAlignment(QtCore.Qt.AlignCenter)
        self.desarollo_text.setObjectName("desarollo_text")
        self.desarrollo_input = QtWidgets.QTextEdit(self.grupo3)
        self.desarrollo_input.setGeometry(QtCore.QRect(10, 240, 381, 171))
        self.desarrollo_input.setObjectName("desarrollo_input")
        self.btn_enviar = QtWidgets.QPushButton(self.FORM)
        self.btn_enviar.setGeometry(QtCore.QRect(800, 450, 181, 41))
        self.btn_enviar.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.btn_enviar.setObjectName("btn_enviar")
        self.btn_cancelar = QtWidgets.QPushButton(self.FORM)
        self.btn_cancelar.setGeometry(QtCore.QRect(580, 450, 171, 41))
        self.btn_cancelar.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.tabWidget.addTab(self.FORM, "")
        self.DESCARGA = QtWidgets.QWidget()
        self.DESCARGA.setObjectName("DESCARGA")
        self.tabWidget.addTab(self.DESCARGA, "")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(10, 0, 971, 61))
        font = QtGui.QFont()
        font.setPointSize(31)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setWordWrap(False)
        self.titulo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.titulo.setObjectName("titulo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CopyFiles"))
        self.folio_text.setText(_translate("MainWindow", "FOLIO"))
        self.turno_text.setText(_translate("MainWindow", "TURNO"))
        self.agente_text.setText(_translate("MainWindow", "AGENTE"))
        self.report_o_text.setText(_translate("MainWindow", "Reporto"))
        self.h_report_text.setText(_translate("MainWindow", "H. Reporte"))
        self.terminal_text.setText(_translate("MainWindow", "H. Terminal"))
        self.reporte_text.setText(_translate("MainWindow", "Reporte"))
        self.mun_region_text.setText(_translate("MainWindow", "Municipio/Region"))
        self.colonia_text.setText(_translate("MainWindow", "Col/Junta Auxiliar"))
        self.colonia_text_2.setText(_translate("MainWindow", "Dir/Parje/Coordenadas"))
        self.dependencias_text.setText(_translate("MainWindow", "Dependencias Participantes"))
        self.acciones_text.setText(_translate("MainWindow", "Acciones de PC"))
        self.afectacion_text.setText(_translate("MainWindow", "Afectación"))
        self.desarollo_text.setText(_translate("MainWindow", "Desarrollo del Reporte"))
        self.btn_enviar.setText(_translate("MainWindow", "Enviar"))
        self.btn_cancelar.setText(_translate("MainWindow", "Cancelar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FORM), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DESCARGA), _translate("MainWindow", "Tab 2"))
        self.titulo.setText(_translate("MainWindow", "PRUEBA TITULO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
