# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'in-PROTECC-CIVIL.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(998, 679)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(998, 679))
        MainWindow.setMaximumSize(QtCore.QSize(998, 679))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 90, 1001, 591))
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_form = QtWidgets.QWidget()
        self.tab_form.setAutoFillBackground(False)
        self.tab_form.setObjectName("tab_form")
        self.grupo1 = QtWidgets.QGroupBox(self.tab_form)
        self.grupo1.setGeometry(QtCore.QRect(10, 20, 561, 201))
        self.grupo1.setTitle("")
        self.grupo1.setObjectName("grupo1")
        self.folio_text = QtWidgets.QLabel(self.grupo1)
        self.folio_text.setEnabled(True)
        self.folio_text.setGeometry(QtCore.QRect(10, 10, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folio_text.sizePolicy().hasHeightForWidth())
        self.folio_text.setSizePolicy(sizePolicy)
        self.folio_text.setMinimumSize(QtCore.QSize(41, 21))
        self.folio_text.setMaximumSize(QtCore.QSize(41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.folio_text.setFont(font)
        self.folio_text.setAlignment(QtCore.Qt.AlignCenter)
        self.folio_text.setObjectName("folio_text")
        self.folio_input = QtWidgets.QLineEdit(self.grupo1)
        self.folio_input.setGeometry(QtCore.QRect(60, 10, 71, 21))
        self.folio_input.setObjectName("folio_input")
        self.turno_text = QtWidgets.QLabel(self.grupo1)
        self.turno_text.setGeometry(QtCore.QRect(150, 10, 51, 21))
        self.turno_text.setMaximumSize(QtCore.QSize(51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.turno_text.setFont(font)
        self.turno_text.setAlignment(QtCore.Qt.AlignCenter)
        self.turno_text.setObjectName("turno_text")
        self.turno_input = QtWidgets.QLineEdit(self.grupo1)
        self.turno_input.setGeometry(QtCore.QRect(210, 10, 91, 21))
        self.turno_input.setObjectName("turno_input")
        self.agente_text = QtWidgets.QLabel(self.grupo1)
        self.agente_text.setGeometry(QtCore.QRect(320, 10, 51, 21))
        self.agente_text.setMaximumSize(QtCore.QSize(51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.agente_text.setFont(font)
        self.agente_text.setAlignment(QtCore.Qt.AlignCenter)
        self.agente_text.setObjectName("agente_text")
        self.agente_input = QtWidgets.QLineEdit(self.grupo1)
        self.agente_input.setGeometry(QtCore.QRect(380, 10, 91, 21))
        self.agente_input.setObjectName("agente_input")
        self.report_o_text = QtWidgets.QLabel(self.grupo1)
        self.report_o_text.setGeometry(QtCore.QRect(10, 80, 71, 21))
        self.report_o_text.setMaximumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.report_o_text.setFont(font)
        self.report_o_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.report_o_text.setObjectName("report_o_text")
        self.report_o_input = QtWidgets.QLineEdit(self.grupo1)
        self.report_o_input.setGeometry(QtCore.QRect(90, 80, 101, 21))
        self.report_o_input.setObjectName("report_o_input")
        self.h_report_text = QtWidgets.QLabel(self.grupo1)
        self.h_report_text.setGeometry(QtCore.QRect(10, 110, 71, 21))
        self.h_report_text.setMaximumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.h_report_text.setFont(font)
        self.h_report_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.h_report_text.setObjectName("h_report_text")
        self.h_report_input = QtWidgets.QLineEdit(self.grupo1)
        self.h_report_input.setGeometry(QtCore.QRect(90, 110, 101, 21))
        self.h_report_input.setObjectName("h_report_input")
        self.terminal_text = QtWidgets.QLabel(self.grupo1)
        self.terminal_text.setGeometry(QtCore.QRect(10, 140, 71, 21))
        self.terminal_text.setMaximumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.terminal_text.setFont(font)
        self.terminal_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.terminal_text.setObjectName("terminal_text")
        self.terminal_input = QtWidgets.QLineEdit(self.grupo1)
        self.terminal_input.setGeometry(QtCore.QRect(90, 140, 101, 21))
        self.terminal_input.setObjectName("terminal_input")
        self.reporte_text = QtWidgets.QLabel(self.grupo1)
        self.reporte_text.setGeometry(QtCore.QRect(10, 170, 71, 21))
        self.reporte_text.setMaximumSize(QtCore.QSize(71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.reporte_text.setFont(font)
        self.reporte_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.reporte_text.setObjectName("reporte_text")
        self.reporte_input = QtWidgets.QLineEdit(self.grupo1)
        self.reporte_input.setGeometry(QtCore.QRect(90, 170, 101, 21))
        self.reporte_input.setObjectName("reporte_input")
        self.mun_region_text = QtWidgets.QLabel(self.grupo1)
        self.mun_region_text.setGeometry(QtCore.QRect(230, 80, 111, 21))
        self.mun_region_text.setMaximumSize(QtCore.QSize(111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.mun_region_text.setFont(font)
        self.mun_region_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mun_region_text.setObjectName("mun_region_text")
        self.mun_region_input = QtWidgets.QLineEdit(self.grupo1)
        self.mun_region_input.setGeometry(QtCore.QRect(360, 80, 191, 21))
        self.mun_region_input.setObjectName("mun_region_input")
        self.colonia_text = QtWidgets.QLabel(self.grupo1)
        self.colonia_text.setGeometry(QtCore.QRect(230, 110, 111, 21))
        self.colonia_text.setMaximumSize(QtCore.QSize(111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.colonia_text.setFont(font)
        self.colonia_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.colonia_text.setObjectName("colonia_text")
        self.colonia_input = QtWidgets.QLineEdit(self.grupo1)
        self.colonia_input.setGeometry(QtCore.QRect(360, 110, 191, 21))
        self.colonia_input.setObjectName("colonia_input")
        self.coord_text = QtWidgets.QLabel(self.grupo1)
        self.coord_text.setGeometry(QtCore.QRect(230, 140, 121, 21))
        self.coord_text.setMaximumSize(QtCore.QSize(121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.coord_text.setFont(font)
        self.coord_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.coord_text.setObjectName("coord_text")
        self.coord_input = QtWidgets.QLineEdit(self.grupo1)
        self.coord_input.setGeometry(QtCore.QRect(360, 140, 191, 21))
        self.coord_input.setObjectName("coord_input")
        self.grupo2 = QtWidgets.QGroupBox(self.tab_form)
        self.grupo2.setGeometry(QtCore.QRect(10, 230, 561, 211))
        self.grupo2.setTitle("")
        self.grupo2.setObjectName("grupo2")
        self.dependencias_text = QtWidgets.QLabel(self.grupo2)
        self.dependencias_text.setGeometry(QtCore.QRect(20, 10, 221, 31))
        self.dependencias_text.setMaximumSize(QtCore.QSize(231, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.dependencias_text.setFont(font)
        self.dependencias_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dependencias_text.setObjectName("dependencias_text")
        self.acciones_text = QtWidgets.QLabel(self.grupo2)
        self.acciones_text.setGeometry(QtCore.QRect(330, 10, 221, 31))
        self.acciones_text.setMaximumSize(QtCore.QSize(231, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.acciones_text.setFont(font)
        self.acciones_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.acciones_text.setObjectName("acciones_text")
        self.dependencias_input = QtWidgets.QPlainTextEdit(self.grupo2)
        self.dependencias_input.setGeometry(QtCore.QRect(10, 50, 231, 151))
        self.dependencias_input.setObjectName("dependencias_input")
        self.acciones_input = QtWidgets.QPlainTextEdit(self.grupo2)
        self.acciones_input.setGeometry(QtCore.QRect(320, 50, 231, 151))
        self.acciones_input.setObjectName("acciones_input")
        self.img_dependencias = QtWidgets.QLabel(self.grupo2)
        self.img_dependencias.setEnabled(False)
        self.img_dependencias.setGeometry(QtCore.QRect(180, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Source Serif Pro")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.img_dependencias.setFont(font)
        self.img_dependencias.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.img_dependencias.setStyleSheet("border-image: url(:/img_1/Dependencias participantes.png);")
        self.img_dependencias.setText("")
        self.img_dependencias.setAlignment(QtCore.Qt.AlignCenter)
        self.img_dependencias.setObjectName("img_dependencias")
        self.img_dependencias_2 = QtWidgets.QLabel(self.grupo2)
        self.img_dependencias_2.setEnabled(False)
        self.img_dependencias_2.setGeometry(QtCore.QRect(430, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Source Serif Pro")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.img_dependencias_2.setFont(font)
        self.img_dependencias_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.img_dependencias_2.setStyleSheet("border-image: url(:/img_1/AccionesPC.png);")
        self.img_dependencias_2.setText("")
        self.img_dependencias_2.setAlignment(QtCore.Qt.AlignCenter)
        self.img_dependencias_2.setObjectName("img_dependencias_2")
        self.grupo3 = QtWidgets.QGroupBox(self.tab_form)
        self.grupo3.setGeometry(QtCore.QRect(580, 20, 401, 421))
        self.grupo3.setTitle("")
        self.grupo3.setObjectName("grupo3")
        self.afectacion_text = QtWidgets.QLabel(self.grupo3)
        self.afectacion_text.setGeometry(QtCore.QRect(20, 10, 371, 21))
        self.afectacion_text.setMaximumSize(QtCore.QSize(381, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.afectacion_text.setFont(font)
        self.afectacion_text.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.afectacion_text.setObjectName("afectacion_text")
        self.desarollo_text = QtWidgets.QLabel(self.grupo3)
        self.desarollo_text.setGeometry(QtCore.QRect(20, 210, 371, 31))
        self.desarollo_text.setMaximumSize(QtCore.QSize(381, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.desarollo_text.setFont(font)
        self.desarollo_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.desarollo_text.setObjectName("desarollo_text")
        self.afectacion_input = QtWidgets.QPlainTextEdit(self.grupo3)
        self.afectacion_input.setGeometry(QtCore.QRect(10, 40, 381, 161))
        self.afectacion_input.setObjectName("afectacion_input")
        self.desarrollo_input = QtWidgets.QPlainTextEdit(self.grupo3)
        self.desarrollo_input.setGeometry(QtCore.QRect(10, 240, 381, 171))
        self.desarrollo_input.setObjectName("desarrollo_input")
        self.img_afectacion = QtWidgets.QLabel(self.grupo3)
        self.img_afectacion.setEnabled(False)
        self.img_afectacion.setGeometry(QtCore.QRect(90, 10, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Source Serif Pro")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.img_afectacion.setFont(font)
        self.img_afectacion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.img_afectacion.setStyleSheet("border-image: url(:/img_1/afectacion.png);")
        self.img_afectacion.setText("")
        self.img_afectacion.setAlignment(QtCore.Qt.AlignCenter)
        self.img_afectacion.setObjectName("img_afectacion")
        self.img_reporte = QtWidgets.QLabel(self.grupo3)
        self.img_reporte.setEnabled(False)
        self.img_reporte.setGeometry(QtCore.QRect(150, 210, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Source Serif Pro")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.img_reporte.setFont(font)
        self.img_reporte.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.img_reporte.setStyleSheet("border-image: url(:/img_1/Reporte.png);")
        self.img_reporte.setText("")
        self.img_reporte.setAlignment(QtCore.Qt.AlignCenter)
        self.img_reporte.setObjectName("img_reporte")
        self.afectacion_input.raise_()
        self.afectacion_text.raise_()
        self.desarollo_text.raise_()
        self.desarrollo_input.raise_()
        self.img_afectacion.raise_()
        self.img_reporte.raise_()
        self.btn_enviar = QtWidgets.QPushButton(self.tab_form)
        self.btn_enviar.setGeometry(QtCore.QRect(810, 500, 171, 41))
        self.btn_enviar.setMaximumSize(QtCore.QSize(171, 41))
        self.btn_enviar.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.btn_enviar.setObjectName("btn_enviar")
        self.btn_cancelar = QtWidgets.QPushButton(self.tab_form)
        self.btn_cancelar.setGeometry(QtCore.QRect(600, 500, 171, 41))
        self.btn_cancelar.setMaximumSize(QtCore.QSize(171, 41))
        self.btn_cancelar.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.fondo_central = QtWidgets.QLabel(self.tab_form)
        self.fondo_central.setEnabled(False)
        self.fondo_central.setGeometry(QtCore.QRect(-100, -130, 1121, 701))
        font = QtGui.QFont()
        font.setFamily("Source Serif Pro")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.fondo_central.setFont(font)
        self.fondo_central.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fondo_central.setStyleSheet("background-image: url(:/img_1/FONDO BLANCO.jpg);")
        self.fondo_central.setText("")
        self.fondo_central.setAlignment(QtCore.Qt.AlignCenter)
        self.fondo_central.setObjectName("fondo_central")
        self.fondo_central.raise_()
        self.grupo1.raise_()
        self.grupo2.raise_()
        self.grupo3.raise_()
        self.btn_enviar.raise_()
        self.btn_cancelar.raise_()
        self.tabWidget.addTab(self.tab_form, "")
        self.tab_descarga_datos = QtWidgets.QWidget()
        self.tab_descarga_datos.setObjectName("tab_descarga_datos")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_descarga_datos)
        self.plainTextEdit.setEnabled(False)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 210, 971, 321))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.grup_op_busqueda = QtWidgets.QGroupBox(self.tab_descarga_datos)
        self.grup_op_busqueda.setGeometry(QtCore.QRect(10, 10, 971, 151))
        self.grup_op_busqueda.setObjectName("grup_op_busqueda")
        self.rbtn_individual = QtWidgets.QRadioButton(self.grup_op_busqueda)
        self.rbtn_individual.setGeometry(QtCore.QRect(20, 20, 72, 17))
        self.rbtn_individual.setChecked(True)
        self.rbtn_individual.setObjectName("rbtn_individual")
        self.rbtn_rangos = QtWidgets.QRadioButton(self.grup_op_busqueda)
        self.rbtn_rangos.setGeometry(QtCore.QRect(600, 20, 83, 18))
        self.rbtn_rangos.setObjectName("rbtn_rangos")
        self.grup_individual = QtWidgets.QGroupBox(self.grup_op_busqueda)
        self.grup_individual.setGeometry(QtCore.QRect(10, 40, 411, 61))
        self.grup_individual.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grup_individual.setTitle("")
        self.grup_individual.setObjectName("grup_individual")
        self.b_folio_input = QtWidgets.QLineEdit(self.grup_individual)
        self.b_folio_input.setGeometry(QtCore.QRect(70, 20, 111, 21))
        self.b_folio_input.setObjectName("b_folio_input")
        self.b_folio_text = QtWidgets.QLabel(self.grup_individual)
        self.b_folio_text.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.b_folio_text.setMaximumSize(QtCore.QSize(61, 21))
        self.b_folio_text.setObjectName("b_folio_text")
        self.b_fecha_text = QtWidgets.QLabel(self.grup_individual)
        self.b_fecha_text.setGeometry(QtCore.QRect(230, 20, 51, 21))
        self.b_fecha_text.setMaximumSize(QtCore.QSize(51, 21))
        self.b_fecha_text.setObjectName("b_fecha_text")
        self.b_fecha_dia_input = QtWidgets.QLineEdit(self.grup_individual)
        self.b_fecha_dia_input.setGeometry(QtCore.QRect(270, 20, 21, 21))
        self.b_fecha_dia_input.setText("")
        self.b_fecha_dia_input.setMaxLength(2)
        self.b_fecha_dia_input.setAlignment(QtCore.Qt.AlignCenter)
        self.b_fecha_dia_input.setObjectName("b_fecha_dia_input")
        self.b_fecha_mes_input = QtWidgets.QLineEdit(self.grup_individual)
        self.b_fecha_mes_input.setGeometry(QtCore.QRect(300, 20, 21, 21))
        self.b_fecha_mes_input.setText("")
        self.b_fecha_mes_input.setMaxLength(2)
        self.b_fecha_mes_input.setAlignment(QtCore.Qt.AlignCenter)
        self.b_fecha_mes_input.setObjectName("b_fecha_mes_input")
        self.b_fecha_anno_input = QtWidgets.QLineEdit(self.grup_individual)
        self.b_fecha_anno_input.setGeometry(QtCore.QRect(330, 20, 61, 21))
        self.b_fecha_anno_input.setText("")
        self.b_fecha_anno_input.setMaxLength(4)
        self.b_fecha_anno_input.setAlignment(QtCore.Qt.AlignCenter)
        self.b_fecha_anno_input.setObjectName("b_fecha_anno_input")
        self.grup_rangos = QtWidgets.QGroupBox(self.grup_op_busqueda)
        self.grup_rangos.setGeometry(QtCore.QRect(430, 40, 531, 61))
        self.grup_rangos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grup_rangos.setTitle("")
        self.grup_rangos.setObjectName("grup_rangos")
        self.rang_fecha1_text = QtWidgets.QLabel(self.grup_rangos)
        self.rang_fecha1_text.setGeometry(QtCore.QRect(10, 30, 41, 21))
        self.rang_fecha1_text.setObjectName("rang_fecha1_text")
        self.rang_fecha1_dia_input = QtWidgets.QLineEdit(self.grup_rangos)
        self.rang_fecha1_dia_input.setGeometry(QtCore.QRect(50, 30, 21, 21))
        self.rang_fecha1_dia_input.setText("")
        self.rang_fecha1_dia_input.setMaxLength(2)
        self.rang_fecha1_dia_input.setAlignment(QtCore.Qt.AlignCenter)
        self.rang_fecha1_dia_input.setObjectName("rang_fecha1_dia_input")
        self.b_fecha_text_3 = QtWidgets.QLabel(self.grup_rangos)
        self.b_fecha_text_3.setGeometry(QtCore.QRect(90, 10, 21, 21))
        self.b_fecha_text_3.setObjectName("b_fecha_text_3")
        self.b_fecha_text_4 = QtWidgets.QLabel(self.grup_rangos)
        self.b_fecha_text_4.setGeometry(QtCore.QRect(280, 10, 21, 21))
        self.b_fecha_text_4.setObjectName("b_fecha_text_4")
        self.rang_fecha1_mes_input = QtWidgets.QLineEdit(self.grup_rangos)
        self.rang_fecha1_mes_input.setGeometry(QtCore.QRect(80, 30, 21, 21))
        self.rang_fecha1_mes_input.setText("")
        self.rang_fecha1_mes_input.setMaxLength(2)
        self.rang_fecha1_mes_input.setAlignment(QtCore.Qt.AlignCenter)
        self.rang_fecha1_mes_input.setObjectName("rang_fecha1_mes_input")
        self.rang_fecha1_anno_input = QtWidgets.QLineEdit(self.grup_rangos)
        self.rang_fecha1_anno_input.setGeometry(QtCore.QRect(110, 30, 51, 21))
        self.rang_fecha1_anno_input.setText("")
        self.rang_fecha1_anno_input.setMaxLength(4)
        self.rang_fecha1_anno_input.setAlignment(QtCore.Qt.AlignCenter)
        self.rang_fecha1_anno_input.setObjectName("rang_fecha1_anno_input")
        self.rang_fecha2_dia_input = QtWidgets.QLineEdit(self.grup_rangos)
        self.rang_fecha2_dia_input.setGeometry(QtCore.QRect(230, 30, 31, 21))
        self.rang_fecha2_dia_input.setText("")
        self.rang_fecha2_dia_input.setMaxLength(2)
        self.rang_fecha2_dia_input.setAlignment(QtCore.Qt.AlignCenter)
        self.rang_fecha2_dia_input.setObjectName("rang_fecha2_dia_input")
        self.rang_fecha2_mes_input = QtWidgets.QLineEdit(self.grup_rangos)
        self.rang_fecha2_mes_input.setGeometry(QtCore.QRect(270, 30, 31, 21))
        self.rang_fecha2_mes_input.setText("")
        self.rang_fecha2_mes_input.setMaxLength(2)
        self.rang_fecha2_mes_input.setAlignment(QtCore.Qt.AlignCenter)
        self.rang_fecha2_mes_input.setObjectName("rang_fecha2_mes_input")
        self.rang_fecha2_anno_input = QtWidgets.QLineEdit(self.grup_rangos)
        self.rang_fecha2_anno_input.setGeometry(QtCore.QRect(310, 30, 51, 21))
        self.rang_fecha2_anno_input.setText("")
        self.rang_fecha2_anno_input.setMaxLength(4)
        self.rang_fecha2_anno_input.setAlignment(QtCore.Qt.AlignCenter)
        self.rang_fecha2_anno_input.setObjectName("rang_fecha2_anno_input")
        self.rang_fecha2_text = QtWidgets.QLabel(self.grup_rangos)
        self.rang_fecha2_text.setGeometry(QtCore.QRect(180, 30, 41, 21))
        self.rang_fecha2_text.setObjectName("rang_fecha2_text")
        self.btn_buscar_datos = QtWidgets.QPushButton(self.grup_op_busqueda)
        self.btn_buscar_datos.setGeometry(QtCore.QRect(360, 110, 121, 31))
        self.btn_buscar_datos.setObjectName("btn_buscar_datos")
        self.btn_directorio_excel = QtWidgets.QPushButton(self.tab_descarga_datos)
        self.btn_directorio_excel.setGeometry(QtCore.QRect(860, 170, 41, 21))
        self.btn_directorio_excel.setObjectName("btn_directorio_excel")
        self.directorio_g_text = QtWidgets.QLabel(self.tab_descarga_datos)
        self.directorio_g_text.setGeometry(QtCore.QRect(80, 170, 71, 21))
        self.directorio_g_text.setObjectName("directorio_g_text")
        self.directorio_g_input = QtWidgets.QLineEdit(self.tab_descarga_datos)
        self.directorio_g_input.setEnabled(False)
        self.directorio_g_input.setGeometry(QtCore.QRect(160, 170, 681, 21))
        self.directorio_g_input.setObjectName("directorio_g_input")
        self.tabWidget.addTab(self.tab_descarga_datos, "")
        self.config = QtWidgets.QWidget()
        self.config.setObjectName("config")
        self.groupBox = QtWidgets.QGroupBox(self.config)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 971, 101))
        self.groupBox.setObjectName("groupBox")
        self.ruta_guardado_text = QtWidgets.QLabel(self.groupBox)
        self.ruta_guardado_text.setGeometry(QtCore.QRect(10, 40, 141, 16))
        self.ruta_guardado_text.setObjectName("ruta_guardado_text")
        self.ruta_guardado_input = QtWidgets.QLineEdit(self.groupBox)
        self.ruta_guardado_input.setEnabled(False)
        self.ruta_guardado_input.setGeometry(QtCore.QRect(150, 40, 741, 20))
        self.ruta_guardado_input.setObjectName("ruta_guardado_input")
        self.btn_guardar = QtWidgets.QPushButton(self.groupBox)
        self.btn_guardar.setGeometry(QtCore.QRect(840, 70, 51, 23))
        self.btn_guardar.setObjectName("btn_guardar")
        self.tabWidget.addTab(self.config, "")
        self.titulo_1 = QtWidgets.QLabel(self.centralwidget)
        self.titulo_1.setEnabled(False)
        self.titulo_1.setGeometry(QtCore.QRect(320, 20, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro Semibold")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.titulo_1.setFont(font)
        self.titulo_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titulo_1.setStyleSheet("")
        self.titulo_1.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_1.setObjectName("titulo_1")
        self.titulo2 = QtWidgets.QLabel(self.centralwidget)
        self.titulo2.setEnabled(False)
        self.titulo2.setGeometry(QtCore.QRect(320, 60, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro Semibold")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.titulo2.setFont(font)
        self.titulo2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titulo2.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo2.setObjectName("titulo2")
        self.subtitulo_1 = QtWidgets.QLabel(self.centralwidget)
        self.subtitulo_1.setEnabled(False)
        self.subtitulo_1.setGeometry(QtCore.QRect(40, 10, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Source Serif Pro")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.subtitulo_1.setFont(font)
        self.subtitulo_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.subtitulo_1.setStyleSheet("")
        self.subtitulo_1.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitulo_1.setObjectName("subtitulo_1")
        self.subtitulo_2 = QtWidgets.QLabel(self.centralwidget)
        self.subtitulo_2.setEnabled(False)
        self.subtitulo_2.setGeometry(QtCore.QRect(160, 10, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Source Serif Pro")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.subtitulo_2.setFont(font)
        self.subtitulo_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.subtitulo_2.setStyleSheet("")
        self.subtitulo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitulo_2.setObjectName("subtitulo_2")
        self.logo_secund = QtWidgets.QLabel(self.centralwidget)
        self.logo_secund.setEnabled(False)
        self.logo_secund.setGeometry(QtCore.QRect(10, 0, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Source Serif Pro")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.logo_secund.setFont(font)
        self.logo_secund.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.logo_secund.setStyleSheet("border-image: url(:/img_1/ICONO 2020.png);")
        self.logo_secund.setText("")
        self.logo_secund.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_secund.setObjectName("logo_secund")
        self.logo_secund_3 = QtWidgets.QLabel(self.centralwidget)
        self.logo_secund_3.setEnabled(False)
        self.logo_secund_3.setGeometry(QtCore.QRect(730, 30, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Source Serif Pro")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.logo_secund_3.setFont(font)
        self.logo_secund_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.logo_secund_3.setStyleSheet("border-image: url(:/img_1/LOGO 2020.png);")
        self.logo_secund_3.setText("")
        self.logo_secund_3.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_secund_3.setObjectName("logo_secund_3")
        self.fondo_top = QtWidgets.QLabel(self.centralwidget)
        self.fondo_top.setEnabled(False)
        self.fondo_top.setGeometry(QtCore.QRect(-70, 0, 1121, 131))
        font = QtGui.QFont()
        font.setFamily("Source Serif Pro")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.fondo_top.setFont(font)
        self.fondo_top.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fondo_top.setStyleSheet("background-image: url(:/img_1/FONDO BLANCO.jpg);")
        self.fondo_top.setText("")
        self.fondo_top.setAlignment(QtCore.Qt.AlignCenter)
        self.fondo_top.setObjectName("fondo_top")
        self.fondo_top.raise_()
        self.tabWidget.raise_()
        self.titulo_1.raise_()
        self.titulo2.raise_()
        self.subtitulo_1.raise_()
        self.subtitulo_2.raise_()
        self.logo_secund.raise_()
        self.logo_secund_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PROTECCION CIVIL"))
        self.folio_text.setText(_translate("MainWindow", "FOLIO"))
        self.turno_text.setText(_translate("MainWindow", "TURNO"))
        self.agente_text.setText(_translate("MainWindow", "AGENTE"))
        self.report_o_text.setText(_translate("MainWindow", "Reporto"))
        self.h_report_text.setText(_translate("MainWindow", "H. Reporte"))
        self.terminal_text.setText(_translate("MainWindow", "H. Terminal"))
        self.reporte_text.setText(_translate("MainWindow", "Reporte"))
        self.mun_region_text.setText(_translate("MainWindow", "Municipio/Region"))
        self.colonia_text.setText(_translate("MainWindow", "Col/Junta Auxiliar"))
        self.coord_text.setText(_translate("MainWindow", "Dir/Parje/Coordenadas"))
        self.dependencias_text.setText(_translate("MainWindow", "Dependencias Participantes"))
        self.acciones_text.setText(_translate("MainWindow", "Acciones de PC"))
        self.afectacion_text.setText(_translate("MainWindow", "Afectación"))
        self.desarollo_text.setText(_translate("MainWindow", "Desarrollo del Reporte"))
        self.btn_enviar.setText(_translate("MainWindow", "Enviar"))
        self.btn_cancelar.setText(_translate("MainWindow", "Cancelar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_form), _translate("MainWindow", "FORMULARIO"))
        self.grup_op_busqueda.setTitle(_translate("MainWindow", "OPCIONES DE BUSQUEDA Y EXPORTACIÓN"))
        self.rbtn_individual.setText(_translate("MainWindow", "Individual"))
        self.rbtn_rangos.setText(_translate("MainWindow", "Rangos"))
        self.b_folio_text.setText(_translate("MainWindow", "FOLIO*"))
        self.b_fecha_text.setText(_translate("MainWindow", "FECHA"))
        self.rang_fecha1_text.setText(_translate("MainWindow", "FECHA*"))
        self.b_fecha_text_3.setText(_translate("MainWindow", "DE"))
        self.b_fecha_text_4.setText(_translate("MainWindow", "A"))
        self.rang_fecha2_text.setText(_translate("MainWindow", "FECHA*"))
        self.btn_buscar_datos.setText(_translate("MainWindow", "BUSCAR Y EXPORTAR"))
        self.btn_directorio_excel.setText(_translate("MainWindow", "..."))
        self.directorio_g_text.setText(_translate("MainWindow", "Guardar en*:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_descarga_datos), _translate("MainWindow", "OBTENER DATOS"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.ruta_guardado_text.setText(_translate("MainWindow", "Ruta de guardado de datos*"))
        self.btn_guardar.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config), _translate("MainWindow", "CONFIGURACION"))
        self.titulo_1.setText(_translate("MainWindow", "CENTRO DE ANÁLISIS"))
        self.titulo2.setText(_translate("MainWindow", "CAPTURA DE DATOS"))
        self.subtitulo_1.setText(_translate("MainWindow", "PROTECCION CIVIL"))
        self.subtitulo_2.setText(_translate("MainWindow", "ESTATAL DE PUEBLA"))

import source



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
